routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\EventController;
use App\Http\Controllers\Admin\PosterController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\StatisticController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\SchoolUnitController;
use App\Http\Controllers\Admin\PendaftaranController;
use App\Http\Controllers\Admin\RelatedLinkController;
use App\Http\Controllers\Admin\TahunAjaranController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\GalleryPhotoController;
use App\Http\Controllers\Admin\GalleryVideoController;

Route::get('/', [FrontendController::class, 'index'])->name('index');
Route::get('hubungi-kami.html', [FrontendController::class, 'contactUs'])->name('contactUs');
Route::post('hubungi-kami.html', [FrontendController::class, 'contactUsStore'])->name('contactUs.store');
Route::get('pendaftaran.html', [FrontendController::class, 'register'])->name('register');
Route::get('{slug}.html', [FrontendController::class, 'pageDetail'])->name('pageDetail');
Route::get('/profil/{slug}.html', [FrontendController::class, 'profile'])->name('profile');
Route::get('/lembaga-pendidikan/{slug}.html', [FrontendController::class, 'schoolUnit'])->name('schoolUnit');
Route::get('{lp}/agenda/{slug}.html', [FrontendController::class, 'eventDetail'])->name('eventDetail');
Route::get('{lp}/galeri-foto.html', [FrontendController::class, 'galleryPhotos'])->name('galleryPhotos');
Route::get('{lp}/galeri-foto/{slug}.html', [FrontendController::class, 'galleryPhotoDetail'])->name('galleryPhotoDetail');
Route::get('{lp}/galeri-video.html', [FrontendController::class, 'galleryVideos'])->name('galleryVideos');
Route::get('{lp}/galeri-video/{slug}.html', [FrontendController::class, 'galleryVideoDetail'])->name('galleryVideoDetail');
Route::get('{lp}/poster.html', [FrontendController::class, 'posters'])->name('posters');
Route::get('{lp}/poster/{slug}.html', [FrontendController::class, 'posterDetail'])->name('posterDetail');
Route::get('{lp}/blog.html', [FrontendController::class, 'blog'])->name('blog');
Route::get('{lp}/pendaftaran.html', [FrontendController::class, 'registerForm'])->name('registerForm');
Route::post('pendaftaran/store', [FrontendController::class, 'registerStore'])->name('registerStore');
Route::get('{lp}/{category}.html', [FrontendController::class, 'articles'])->name('articles');
Route::get('{lp}/{category}/{slug}.html', [FrontendController::class, 'articleDetail'])->name('articleDetail');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');

    // Permissions
    Route::resource('permissions', PermissionController::class, ['except' => ['store', 'update', 'destroy']]);

    // Roles
    Route::resource('roles', RoleController::class, ['except' => ['store', 'update', 'destroy']]);

    // Users
    Route::resource('users', UserController::class, ['except' => ['store', 'update', 'destroy']]);

    // School Unit
    Route::post('school-units/media', [SchoolUnitController::class, 'storeMedia'])->name('school-units.storeMedia');
    Route::resource('school-units', SchoolUnitController::class, ['except' => ['store', 'update', 'destroy']]);

    // Category
    Route::resource('categories', CategoryController::class, ['except' => ['store', 'update', 'destroy']]);

    // Article
    Route::post('articles/media', [ArticleController::class, 'storeMedia'])->name('articles.storeMedia');
    Route::resource('articles', ArticleController::class, ['except' => ['store', 'update', 'destroy']]);

    // Event
    Route::post('events/media', [EventController::class, 'storeMedia'])->name('events.storeMedia');
    Route::resource('events', EventController::class, ['except' => ['store', 'update', 'destroy']]);

    // Pages
    Route::resource('pages', PageController::class, ['except' => ['store', 'update', 'destroy']]);

    // Gallery Photo
    Route::post('gallery-photos/media', [GalleryPhotoController::class, 'storeMedia'])->name('gallery-photos.storeMedia');
    Route::resource('gallery-photos', GalleryPhotoController::class, ['except' => ['store', 'update', 'destroy']]);

    // Gallery Video
    Route::resource('gallery-videos', GalleryVideoController::class, ['except' => ['store', 'update', 'destroy']]);

    // Poster
    Route::post('posters/media', [PosterController::class, 'storeMedia'])->name('posters.storeMedia');
    Route::resource('posters', PosterController::class, ['except' => ['store', 'update', 'destroy']]);

    // Slider
    Route::post('sliders/media', [SliderController::class, 'storeMedia'])->name('sliders.storeMedia');
    Route::resource('sliders', SliderController::class, ['except' => ['store', 'update', 'destroy']]);

    // Statistic
    Route::resource('statistics', StatisticController::class, ['except' => ['store', 'update', 'destroy']]);

    // Related Link
    Route::post('related-links/media', [RelatedLinkController::class, 'storeMedia'])->name('related-links.storeMedia');
    Route::resource('related-links', RelatedLinkController::class, ['except' => ['store', 'update', 'destroy']]);

    // Testimonial
    Route::post('testimonials/media', [TestimonialController::class, 'storeMedia'])->name('testimonials.storeMedia');
    Route::resource('testimonials', TestimonialController::class, ['except' => ['store', 'update', 'destroy']]);

    // Contact Us
    Route::resource('contactuses', ContactUsController::class, ['except' => ['store', 'update', 'destroy']]);

    // Pendaftaran
    Route::resource('pendaftarans', PendaftaranController::class, ['except' => ['store', 'update', 'destroy']]);

    // Tahun Ajaran
    Route::resource('tahun-ajarans', TahunAjaranController::class, ['except' => ['store', 'update', 'destroy']]);
    Route::get('tahun-ajarans/{tahunAjaran}/export', [TahunAjaranController::class, 'export'])->name('tahun-ajarans.export');
});

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Article;
use Gate;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ArticleController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('article_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.article.index');
    }

    public function create()
    {
        abort_if(Gate::denies('article_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.article.create');
    }

    public function edit(Article $article)
    {
        abort_if(Gate::denies('article_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.article.edit', compact('article'));
    }

    public function show(Article $article)
    {
        abort_if(Gate::denies('article_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $article->load('schoolUnit', 'category');

        return view('admin.article.show', compact('article'));
    }

    public function storeMedia(Request $request)
    {
        abort_if(Gate::none(['article_create', 'article_edit']), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->has('size')) {
            $this->validate($request, [
                'file' => 'max:' . $request->input('size') * 1024,
            ]);
        }
        if (request()->has('max_width') || request()->has('max_height')) {
            $this->validate(request(), [
                'file' => sprintf(
                'image|dimensions:max_width=%s,max_height=%s',
                request()->input('max_width', 100000),
                request()->input('max_height', 100000)
                ),
            ]);
        }

        $model                     = new Article();
        $model->id                 = $request->input('model_id', 0);
        $model->exists             = true;
        $media                     = $model->addMediaFromRequest('file')->toMediaCollection($request->input('collection_name'));
        $media->wasRecentlyCreated = true;

        return response()->json(compact('media'), Response::HTTP_CREATED);
    }
}

app/Http/Livewire/Article/Create.php
<?php

namespace App\Http\Livewire\Article;

use App\Models\Article;
use App\Models\Category;
use App\Models\SchoolUnit;
use Livewire\Component;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Create extends Component
{
    public Article $article;

    public array $mediaToRemove = [];

    public array $listsForFields = [];

    public array $mediaCollections = [];

    public function mount(Article $article)
    {
        $this->article            = $article;
        $this->article->is_slider = '1';
        $this->initListsForFields();
    }

    public function render()
    {
        return view('livewire.article.create');
    }

    public function submit()
    {
        $this->validate();
        if (auth()->user()->school_unit_id != 0) {
            $this->article->school_unit_id = auth()->user()->school_unit_id;
        }
        $this->article->save();
        $this->syncMedia();

        return redirect()->route('admin.articles.index');
    }

    public function addMedia($media): void
    {
        $this->mediaCollections[$media['collection_name']][] = $media;
    }

    public function removeMedia($media): void
    {
        $collection = collect($this->mediaCollections[$media['collection_name']]);

        $this->mediaCollections[$media['collection_name']] = $collection->reject(fn ($item) => $item['uuid'] === $media['uuid'])->toArray();

        $this->mediaToRemove[] = $media['uuid'];
    }

    protected function rules(): array
    {
        return [
            'article.slug' => [
                'string',
                'nullable',
            ],
            'article.title' => [
                'string',
                'nullable',
            ],
            'article.content' => [
                'string',
                'nullable',
            ],
            'mediaCollections.article_cover' => [
                'array',
                'nullable',
            ],
            'mediaCollections.article_cover.*.id' => [
                'integer',
                'exists:media,id',
            ],
            'article.school_unit_id' => [
                'integer',
                'exists:school_units,id',
                'nullable',
            ],
            'article.category_id' => [
                'integer',
                'exists:categories,id',
                'nullable',
            ],
            'article.published_at' => [
                'nullable',
                'date_format:' . config('project.datetime_format'),
            ],
            'article.is_slider' => [
                'nullable',
                'in:' . implode(',', array_keys($this->listsForFields['is_slider'])),
            ],
        ];
    }

    protected function initListsForFields(): void
    {
        $this->listsForFields['school_unit'] = SchoolUnit::pluck('name', 'id');
        $this->listsForFields['category']     = Category::pluck('name', 'id');
        $this->listsForFields['is_slider']    = $this->article::IS_SLIDER_RADIO;
    }

    protected function syncMedia(): void
    {
        collect($this->mediaCollections)->flatten(1)
            ->each(fn ($item) => Media::where('uuid', $item['uuid'])
            ->update(['model_id' => $this->article->id]));

        Media::whereIn('uuid', $this->mediaToRemove)->delete();
    }
}

app/Http/Livewire/Article/Edit.php
<?php

namespace App\Http\Livewire\Article;

use App\Models\Article;
use App\Models\Category;
use App\Models\SchoolUnit;
use Livewire\Component;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Edit extends Component
{
    public Article $article;

    public array $mediaToRemove = [];

    public array $listsForFields = [];

    public array $mediaCollections = [];

    public function mount(Article $article)
    {
        $this->article = $article;
        $this->initListsForFields();
        $this->mediaCollections = [
            'article_cover' => $article->cover,
        ];
    }

    public function render()
    {
        return view('livewire.article.edit');
    }

    public function submit()
    {
        $this->validate();

        $this->article->save();
        $this->syncMedia();
        $this->emit('reinit');

        return redirect()->route('admin.articles.index');
    }

    public function addMedia($media): void
    {
        $this->mediaCollections[$media['collection_name']][] = $media;
    }

    public function removeMedia($media): void
    {
        $collection = collect($this->mediaCollections[$media['collection_name']]);

        $this->mediaCollections[$media['collection_name']] = $collection->reject(fn ($item) => $item['uuid'] === $media['uuid'])->toArray();

        $this->mediaToRemove[] = $media['uuid'];
    }

    public function getMediaCollection($name)
    {
        return $this->mediaCollections[$name];
    }

    protected function rules(): array
    {
        return [
            'article.slug' => [
                'string',
                'nullable',
            ],
            'article.title' => [
                'string',
                'nullable',
            ],
            'article.content' => [
                'string',
                'nullable',
            ],
            'mediaCollections.article_cover' => [
                'array',
                'nullable',
            ],
            'mediaCollections.article_cover.*.id' => [
                'integer',
                'exists:media,id',
            ],
            'article.school_unit_id' => [
                'integer',
                'exists:school_units,id',
                'nullable',
            ],
            'article.category_id' => [
                'integer',
                'exists:categories,id',
                'nullable',
            ],
            'article.published_at' => [
                'nullable',
                'date_format:' . config('project.datetime_format'),
            ],
            'article.is_slider' => [
                'nullable',
                'in:' . implode(',', array_keys($this->listsForFields['is_slider'])),
            ],
        ];
    }

    protected function initListsForFields(): void
    {
        $this->listsForFields['school_unit'] = SchoolUnit::pluck('name', 'id');
        $this->listsForFields['category']     = Category::pluck('name', 'id');
        $this->listsForFields['is_slider']    = $this->article::IS_SLIDER_RADIO;
    }

    protected function syncMedia(): void
    {
        collect($this->mediaCollections)->flatten(1)
            ->each(fn ($item) => Media::where('uuid', $item['uuid'])
            ->update(['model_id' => $this->article->id]));

        Media::whereIn('uuid', $this->mediaToRemove)->delete();
    }
}

app/Http/Livewire/Article/Index.php
<?php

namespace App\Http\Livewire\Article;

use App\Http\Livewire\WithConfirmation;
use App\Http\Livewire\WithSorting;
use App\Models\Article;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;
use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination;
    use WithSorting;
    use WithConfirmation;

    public int $perPage;

    public array $orderable;

    public string $search = '';

    public array $selected = [];

    public array $paginationOptions;

    protected $queryString = [
        'search' => [
            'except' => '',
        ],
        'sortBy' => [
            'except' => 'id',
        ],
        'sortDirection' => [
            'except' => 'asc',
        ],
    ];

    public function getSelectedCountProperty()
    {
        return count($this->selected);
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function updatingPerPage()
    {
        $this->resetPage();
    }

    public function resetSelected()
    {
        $this->selected = [];
    }

    public function mount()
    {
        $this->sortBy            = 'id';
        $this->sortDirection     = 'asc';
        $this->perPage           = 25;
        $this->paginationOptions = config('project.pagination.options');
        $this->orderable         = (new Article())->orderable;
    }

    public function render()
    {
        $query = Article::with(['schoolUnit', 'category'])->latest()->advancedFilter([
            's'               => $this->search ?: null,
            'order_column'    => $this->sortBy,
            'order_direction' => $this->sortDirection,
        ]);

        if (auth()->user()->school_unit_id != 0) {
            $query->where('school_unit_id', auth()->user()->school_unit_id);
        }

        $articles = $query->paginate($this->perPage);

        return view('livewire.article.index', compact('query', 'articles', 'articles'));
    }

    public function deleteSelected()
    {
        abort_if(Gate::denies('article_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        Article::whereIn('id', $this->selected)->delete();

        $this->resetSelected();
    }

    public function delete(Article $article)
    {
        abort_if(Gate::denies('article_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $article->delete();
    }
}

resources/views/livewire/article/create.blade.php
<form wire:submit.prevent="submit" class="pt-3">

    <div class="form-group {{ $errors->has('article.title') ? 'invalid' : '' }}">
        <label class="form-label" for="title">{{ trans('cruds.article.fields.title') }}</label>
        <input class="form-control" type="text" name="title" id="title" wire:model.defer="article.title">
        <div class="validation-message">
            {{ $errors->first('article.title') }}
        </div>
        <div class="help-block">
            {{ trans('cruds.article.fields.title_helper') }}
        </div>
    </div>
    <div class="form-group {{ $errors->has('article.content') ? 'invalid' : '' }}" wire:ignore>
        <label class="form-label" for="content">{{ trans('cruds.article.fields.content') }}</label>
        <textarea
            class="form-control"
            id="content"
            wire:model.defer="article.content"
            wire:key="ckeditor-1"
            x-data
            x-init="
            CKEDITOR.replace('content', {
                filebrowserImageBrowseUrl: '/filemanager?type=Images',
                filebrowserBrowseUrl: '/filemanager?type=Files',
            });
            CKEDITOR.instances.content.on('change', function() {
                $dispatch('input', this.getData());
            });"
            >
        </textarea>
        <div class="validation-message">
            {{ $errors->first('article.content') }}
        </div>
        <div class="help-block">
            {{ trans('cruds.article.fields.content_helper') }}
        </div>
    </div>
    <div class="form-group {{ $errors->has('mediaCollections.article_cover') ? 'invalid' : '' }}">
        <label class="form-label" for="cover">{{ trans('cruds.article.fields.cover') }}</label>
        <x-dropzone id="cover" name="cover" action="{{ route('admin.articles.storeMedia') }}" collection-name="article_cover" max-file-size="1" max-width="4096" max-height="4096" max-files="1" />
        <div class="validation-message">
            {{ $errors->first('mediaCollections.article_cover') }}
        </div>
        <div class="help-block">
            {{ trans('cruds.article.fields.cover_helper') }}
        </div>
    </div>
    @if (auth()->user()->school_unit_id == 0)
    <div class="form-group {{ $errors->has('article.school_unit_id') ? 'invalid' : '' }}">
        <label class="form-label" for="school_unit">{{ trans('cruds.article.fields.school_unit') }}</label>
        <x-select-list class="form-control" id="school_unit" name="school_unit" :options="$listsForFields['school_unit']" wire:model="article.school_unit_id" />
        <div class="validation-message">
            {{ $errors->first('article.school_unit_id') }}
        </div>
        <div class="help-block">
            {{ trans('cruds.article.fields.school_unit_helper') }}
        </div>
    </div>
    @else
    <input type="hidden" name="school_unit" value="{{ auth()->user()->school_unit_id }}">
    @endif

    <div class="form-group {{ $errors->has('article.category_id') ? 'invalid' : '' }}">
        <label class="form-label" for="category">{{ trans('cruds.article.fields.category') }}</label>
        <x-select-list class="form-control" id="category" name="category" :options="$listsForFields['category']" wire:model="article.category_id" />
        <div class="validation-message">
            {{ $errors->first('article.category_id') }}
        </div>
        <div class="help-block">
            {{ trans('cruds.article.fields.category_helper') }}
        </div>
    </div>
    <div class="form-group {{ $errors->has('article.published_at') ? 'invalid' : '' }}">
        <label class="form-label" for="published_at">{{ trans('cruds.article.fields.published_at') }}</label>
        <x-date-picker class="form-control" wire:model="article.published_at" id="published_at" name="published_at" />
        <div class="validation-message">
            {{ $errors->first('article.published_at') }}
        </div>
        <div class="help-block">
            {{ trans('cruds.article.fields.published_at_helper') }}
        </div>
    </div>
    {{-- <div class="form-group {{ $errors->has('article.is_slider') ? 'invalid' : '' }}">
        <label class="form-label">{{ trans('cruds.article.fields.is_slider') }}</label>
        @foreach($listsForFields['is_slider'] as $key => $value)
            <label class="radio-label"><input type="radio" name="is_slider" wire:model="article.is_slider" value="{{ $key }}">{{ $value }}</label>
        @endforeach
        <div class="validation-message">
            {{ $errors->first('article.is_slider') }}
        </div>
        <div class="help-block">
            {{ trans('cruds.article.fields.is_slider_helper') }}
        </div>
    </div> --}}

    <div class="form-group">
        <button class="mr-2 btn btn-indigo" type="submit">
            {{ trans('global.save') }}
        </button>
        <a href="{{ route('admin.articles.index') }}" class="btn btn-secondary">
            {{ trans('global.cancel') }}
        </a>
    </div>
</form>

resources/views/livewire/article/index.blade.php
<div>
    <div class="card-controls sm:flex">
        <div class="w-full sm:w-1/2">
            Per page:
            <select wire:model="perPage" class="form-select w-full sm:w-1/6">
                @foreach($paginationOptions as $value)
                    <option value="{{ $value }}">{{ $value }}</option>
                @endforeach
            </select>

            <button class="btn btn-rose ml-3 disabled:opacity-50 disabled:cursor-not-allowed" type="button" wire:click="confirm('deleteSelected')" wire:loading.attr="disabled" {{ $this->selectedCount ? '' : 'disabled' }}>
                {{ __('Delete Selected') }}
            </button>

        </div>
        <div class="w-full sm:w-1/2 sm:text-right">
            Search:
            <input type="text" wire:model.debounce.300ms="search" class="w-full sm:w-1/3 inline-block" />
        </div>
    </div>
    <div wire:loading.delay class="col-12 alert alert-info">
        Loading...
    </div>
    <table class="table table-index w-full">
        <thead>
            <tr>
                <th class="w-9">
                </th>
                <th class="w-28">
                    NO
                </th>
                <th>
                    {{ trans('cruds.article.fields.title') }}
                    @include('components.table.sort', ['field' => 'title'])
                </th>
                <th>
                    {{ trans('cruds.article.fields.school_unit') }}
                    @include('components.table.sort', ['field' => 'school_unit.name'])
                </th>
                <th>
                    {{ trans('cruds.article.fields.category') }}
                    @include('components.table.sort', ['field' => 'category.name'])
                </th>
                <th>
                    {{ trans('cruds.article.fields.published_at') }}
                    @include('components.table.sort', ['field' => 'published_at'])
                </th>
                <th>
                    visit
                    @include('components.table.sort', ['field' => 'visit'])
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @forelse($articles as $article)
                <tr>
                    <td>
                        <input type="checkbox" value="{{ $article->id }}" wire:model="selected">
                    </td>
                    <td width="1%">
                        {{ $loop->iteration }}
                    </td>
                    <td>
                        {{ Str::limit($article->title, 50) }}
                    </td>
                    <td>
                        @if($article->schoolUnit)
                            <span class="badge badge-relationship">{{ $article->schoolUnit->name ?? '' }}</span>
                        @endif
                    </td>
                    <td>
                        @if($article->category)
                        @if ($article->category->name == 'Berita')
                        <span class="badge badge-info">{{ $article->category->name ?? '' }}</span>
                        @elseif ($article->category->name == 'Pengumuman')
                        <span class="badge badge-success">{{ $article->category->name ?? '' }}</span>
                        @elseif ($article->category->name == 'Artikel')
                        <span class="badge badge-primary">{{ $article->category->name ?? '' }}</span>
                        @else
                        <span class="badge badge-danger">No Kategori</span>
                        @endif
                        @endif
                    </td>
                    <td>
                        {{ Date::parse($article->published_at)->diffForHumans() }}
                    </td>
                    <td>
                        {{ $article->visit ?? '0' }} View
                    </td>
                    <td>
                        <div class="flex justify-end">
                            @can('article_show')
                                <a class="btn btn-sm btn-info mr-2" href="{{ route('admin.articles.show', $article) }}">
                                    {{ trans('global.view') }}
                                </a>
                            @endcan
                            @can('article_edit')
                                <a class="btn btn-sm btn-success mr-2" href="{{ route('admin.articles.edit', $article) }}">
                                    {{ trans('global.edit') }}
                                </a>
                            @endcan
                            @can('article_delete')
                                <button class="btn btn-sm btn-rose mr-2" type="button" wire:click="confirm('delete', {{ $article->id }})" wire:loading.attr="disabled">
                                    {{ trans('global.delete') }}
                                </button>
                            @endcan
                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="10">No entries found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="card-body">
        <div class="pt-3">
            @if($this->selectedCount)
                <p class="text-sm leading-5">
                    <span class="font-medium">
                        {{ $this->selectedCount }}
                    </span>
                    {{ __('Entries selected') }}
                </p>
            @endif
            {{ $articles->links() }}
        </div>
    </div>
</div>

@push('scripts')
    <script>
        Livewire.on('confirm', e => {
    if (!confirm("{{ trans('global.areYouSure') }}")) {
        return
    }
@this[e.callback](...e.argv)
})
    </script>
@endpush